### ISSUE TITLE
Template deprecations in latest version of Vue (1.0.25)

### ISSUE THREAD

**Issue by rivendare** [vuejs-templates/simple#1]
e.g. "vue.js:2129 [Vue warn]: href="{{ docsURL }}": Interpolation inside attributes has been deprecated. Use v-bind or the colon shorthand instead."

**Comment by chrisvfritz** [comment]
The CDN src was using jsDelivr's "latest", which is actually pointing to the 2.0 alpha now - that's why you're getting those warnings. I just updated the CDN src to lock to the latest stable on NPM, which is 1.0.25 as you'd expect. 😄

**Comment by rivendare** [comment]
Ah, my mistake! :)

**Comment by chrisvfritz** [comment]
@rivendare If you _would_ like to try out the 2.0 alpha though, I just added [this template](https://github.com/vuejs-templates/simple-2.0). 😃

**Comment by rivendare** [comment]
Perfect, thanks!
