### ISSUE TITLE
Strange slashes

### ISSUE THREAD

**Issue by dmitry-kurmanov** [vuejs-templates/simple#6]
Why do we need these slashes?  http://joxi.ru/Vm6RdpziJ54DmZ

**Comment by chrisvfritz** [comment]
It tells the vue-cli template compiler not to parse these as mustache tags when creating a new project. They do not appear in the generated project.

**Comment by dmitry-kurmanov** [comment]
I understand it thanks. I just copy simple/template/index.html without vue-cli.
